TAIGA_HOSTNAME: 192.168.1.152
SECRET_KEY: fasdfadsg3qret34542fgvfd


RE_CLONE_SRC_FROM_GIT: False

HOME_TAIGA: /home/taiga

back_end:
  git-repo: https://github.com/taigaio/taiga-back.git
  CONFIG_HOST: ./backend
  SRC_HOST: ./backend/src
  SRC_CONTAINER: /taiga-back
  DATA_HOST: ./taiga-back
  PORT: 8000
API_SERVER: api

front_end:
  BASENAME: taiga-front-dist
  git-repo: https://github.com/taigaio/taiga-front-dist.git
  CONFIG_HOST: ./frontend
  SRC_BASE: ./frontend/src



events:
  BASENAME: taiga-events
  git-repo: https://github.com/taigaio/taiga-events.git
  CONFIG_HOST: ./events
  SRC_BASE: ./events/src
  PORT: 8888
EVENTS_SERVER: events


POSTGRES_SERVER: pg_db
POSTGRES_USER: taiga
POSTGRES_PASSWORD: taiga
POSTGRES_VOLUMN_PATH: ./db/postgres

RABBITMQ_SERVER: rabbitmq
RABBITMQ_HOSTNAME: mymq
RABBITMQ_DEFAULT_USER: taiga
RABBITMQ_DEFAULT_PASS: taiga


